server:
  port: 8900
    
eureka:
  instance:
    hostname: localhost
    
    
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
      - id: phonebook-service
        uri: http://localhost:8082
        predicates:
        - Path=/phonebook/**
        filters: 
          - name: CircuitBreaker
            args:
              name: phonebook-service
              fallbackuri: forward:/phonebookFallback 
              
      - id: user-service
        uri: http://localhost:8081
        predicates:
        - Path=/user/**
        filters: 
         - name: CircuitBreaker
           args:
            name: user-service
            fallbackuri: forward:/userServiceFallback
           
           
           
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
          timeoutInMillieseconds: 5000
          
management:
   endpoints:
    web:
      exposure:
        include: hystrix.stream
        
          